name: Build to DOM Cloud

on:
  push:
    branches:
      - main
  workflow_dispatch:


env:
  BIN_NAME: todo
  SERVER_HOST: sga.domcloud.co

jobs:
  copy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install stable toolchain
      uses: actions-rs/toolchain@v1
    - uses: Swatinem/rust-cache@v1
    - name: Build release binary
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --locked
    - run: mkdir bin && cp ./target/release/${{ env.BIN_NAME }} ./bin/

    - name: Copy to Remote Server
      uses: pierrickdelrieu/scp-action@v0.1.0
      with:
        host: ${{ env.SERVER_HOST }}
        ssh_username: ${{ secrets.SSH_USERNAME }}
        ssh_key: ${{ secrets.SSH_KEY }}
        ssh_passphrase: ''
        source_dir: ./bin
        destination_dir: ./public_html
        rm: true

